### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by gordybullen** [gordybullen/soundup#2]

**Comment by carlosaicrag** [comment]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [ ] Can sign up a user
- [ ] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
## Seeds
- [ ] Adequate and appropriate seeds

**Comment by carlosaicrag** [comment]
opacity background for the modal should be a white color

**Comment by carlosaicrag** [comment]
let's move the create account button that is on the login page and put it at the bottom as smaller text without color

**Comment by carlosaicrag** [comment]
lets change the style of the welcome title at the top of the form.  Right now it looks like a button and i'm tempted to click it even though it is not a button.  Lets just back it black colored text thats a little bit bigger

**Comment by carlosaicrag** [comment]
lets make the errors stack on top of one another instead of side by side

**Comment by carlosaicrag** [comment]
![Screen Shot 2020-06-26 at 1 59 44 PM](https://user-images.githubusercontent.com/30717440/85900815-4bfc2200-b7b5-11ea-95d8-1e700e576263.png)
need to fix these error renders when signing up

**Comment by carlosaicrag** [comment]
need to clear errors when i go from signup to login or login to signup

**Comment by carlosaicrag** [comment]
Heres a reference on how to remove logger from production:
https://open.appacademy.io/learn/swe-in-person/full-stack-project/getting-your-app-production-ready

**Comment by gordybullen** [comment]
> opacity background for the modal should be a white color

Do you mean for the grey background or for the modal content box?
